// Shuttle.ProcessManagement/site.react/src/App.js
import 'jquery';
import 'popper.js';
import 'bootstrap';
import 'bootstrap/dist/css/bootstrap.css';
import './index.css';
import React from 'react';
import Alerts from './Alerts';
import ShuttleBooks from './ShuttleBooks';
import ShuttleOrders from './ShuttleOrders';

function App() {
  return (
    <div>
      <nav className="navbar navbar-dark bg-dark">
        <a className="navbar-brand" href={'#'}>Shuttle Books (react)</a>
        <ul className="navbar-nav flex-row ml-md-auto d-none d-md-flex">
          <li className="nav-item">
            <a
              className="nav-link p-2"
              href={'https://reactjs.org/'}
              target={'_blank'}
              rel="noopener"
              aria-label="Canjs"
            >
              <img
                src={"./logo.png"}
                className="d-inline-block align-middle"
                alt=""
                style={{ width: '20px', height: '20px' }}
              />
            </a>
          </li>
          <li className="nav-item">
            <a
              className="nav-link p-2"
              href={"https://getbootstrap.com/"}
              target={"_blank"}
              rel="noopener"
              aria-label="Bootstrap"
            >
              <img
                src={"./bootstrap-solid.svg"}
                className="d-inline-block align-middle"
                alt=""
                style={{ width: '20px', height: '20px' }}
              />
            </a>
          </li>
          <li className="nav-item">
            <a
              className="nav-link p-2"
              href={"https://react-bootstrap.github.io/"}
              target={"_blank"}
              rel="noopener"
              aria-label="React Bootstrap"
            >
              <img
                src={"./react-bootstrap.svg"}
                className="d-inline-block align-middle"
                alt=""
                style={{ width: '20px', height: '20px' }}
              />
            </a>
          </li>
          <li className="nav-item">
            <a
              className="nav-link p-2"
              href="https://github.com/Shuttle/Shuttle.Esb.Samples/tree/master/Shuttle.ProcessManagement/site.react"
              target={"_blank"}
              rel="noopener"
              aria-label="GitHub"
            >
              <svg
                className="navbar-nav-svg"
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 512 499.36"
                focusable="false"
                style={{ width: '20px', height: '20px' }}
              >
                <title>GitHub</title>
                <path
                  d="M256 0C114.64 0 0 114.61 0 256c0 113.09 73.34 209 175.08 242.9 12.8 2.35 17.47-5.56 17.47-12.34 0-6.08-.22-22.18-.35-43.54-71.2 15.49-86.2-34.34-86.2-34.34-11.64-29.57-28.42-37.45-28.42-37.45-23.27-15.84 1.73-15.55 1.73-15.55 25.69 1.81 39.21 26.38 39.21 26.38 22.84 39.12 59.92 27.82 74.5 21.27 2.33-16.54 8.94-27.82 16.25-34.22-56.84-6.43-116.6-28.43-116.6-126.49 0-27.95 10-50.8 26.35-68.69-2.63-6.48-11.42-32.5 2.51-67.75 0 0 21.49-6.88 70.4 26.24a242.65 242.65 0 0 1 128.18 0c48.87-33.13 70.33-26.24 70.33-26.24 14 35.25 5.18 61.27 2.55 67.75 16.41 17.9 26.31 40.75 26.31 68.69 0 98.35-59.85 120-116.88 126.32 9.19 7.9 17.38 23.53 17.38 47.41 0 34.22-.31 61.83-.31 70.23 0 6.85 4.61 14.81 17.6 12.31C438.72 464.97 512 369.08 512 256.02 512 114.62 397.37 0 256 0z"
                  fill="currentColor"
                  fillRule="evenodd"
                />
              </svg>
            </a>
          </li>
        </ul>
      </nav>
      <Alerts />
      <div className="container-fluid">
      <div className="row row-offcanvas row-offcanvas-left">
        <div id="application-content" className="main col-sm-12 col-md-12 pt-2">
          <ShuttleBooks />
          {/* <ShuttleOrders /> */}
        </div>
      </div>
    </div>
    </div>
  );
}

export default App;

// Shuttle.ProcessManagement/site.vuejs/src/App.vue
<template>
  <div id="app">
    <nav class="navbar navbar-dark bg-dark">
        <a class="navbar-brand" href="#">
            Shuttle Books (vuejs)
        </a>
        <ul class="navbar-nav flex-row ml-md-auto d-none d-md-flex">
            <li class="nav-item">
                <a class="nav-link p-2" href="https://vuejs.org/" target="_blank" rel="noopener" aria-label="Canjs">
                    <img src="./assets/logo.png" class="d-inline-block align-middle" alt="" style="width: 20px; height: 20px;">
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link p-2" href="https://getbootstrap.com/" target="_blank" rel="noopener" aria-label="Bootstrap">
                    <img src="./assets/bootstrap-solid.svg" class="d-inline-block align-middle" alt="" style="width: 20px; height 20px;">
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link p-2" href="https://github.com/Shuttle/Shuttle.Esb.Samples/tree/master/Shuttle.ProcessManagement/site.canjs" target="_blank" rel="noopener" aria-label="GitHub">
                    <svg class="navbar-nav-svg" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 512 499.36"
                            focusable="false" style="width: 20px; height 20px;">
                        <title>GitHub</title>
                        <path d="M256 0C114.64 0 0 114.61 0 256c0 113.09 73.34 209 175.08 242.9 12.8 2.35 17.47-5.56 17.47-12.34 0-6.08-.22-22.18-.35-43.54-71.2 15.49-86.2-34.34-86.2-34.34-11.64-29.57-28.42-37.45-28.42-37.45-23.27-15.84 1.73-15.55 1.73-15.55 25.69 1.81 39.21 26.38 39.21 26.38 22.84 39.12 59.92 27.82 74.5 21.27 2.33-16.54 8.94-27.82 16.25-34.22-56.84-6.43-116.6-28.43-116.6-126.49 0-27.95 10-50.8 26.35-68.69-2.63-6.48-11.42-32.5 2.51-67.75 0 0 21.49-6.88 70.4 26.24a242.65 242.65 0 0 1 128.18 0c48.87-33.13 70.33-26.24 70.33-26.24 14 35.25 5.18 61.27 2.55 67.75 16.41 17.9 26.31 40.75 26.31 68.69 0 98.35-59.85 120-116.88 126.32 9.19 7.9 17.38 23.53 17.38 47.41 0 34.22-.31 61.83-.31 70.23 0 6.85 4.61 14.81 17.6 12.31C438.72 464.97 512 369.08 512 256.02 512 114.62 397.37 0 256 0z" fill="currentColor" fill-rule="evenodd"/>
                    </svg>
                </a>
            </li>
        </ul>
    </nav>
    <!-- <cs-alerts alerts:from="alerts"/> -->
    <br/>
    <div class="container-fluid">
        <div class="row row-offcanvas row-offcanvas-left">
            <div id="application-content" class="main col-sm-12 col-md-12">
                <shuttle-books />
                <shuttle-orders />
            </div>
        </div>
    </div>
  </div>
</template>

<script>
import 'bootstrap/dist/css/bootstrap.css';

import ShuttleBooks from './components/shuttle-books.vue'
import ShuttleOrders from './components/shuttle-orders.vue'

export default {
  name: 'app',
  components: {
    'shuttle-books': ShuttleBooks,
    'shuttle-orders': ShuttleOrders
  }
}
</script>
