// Shuttle.ProcessManagement/site.react/src/ShuttleBooks.js
import React from 'react';
import axios from "axios";
import configuration from "./configuration.js";
import state from "./state.js";
import Card from 'react-bootstrap/Card'
import ProgressBar from 'react-bootstrap/ProgressBar'
import Form from 'react-bootstrap/Form'
import Button from 'react-bootstrap/Button'
import Dropdown from 'react-bootstrap/Dropdown'
import DropdownButton from 'react-bootstrap/DropdownButton'
import ButtonToolbar from 'react-bootstrap/ButtonToolbar'

export default class ShuttleBooks extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            customerName: '',
            customerNameValidation: '',
            customerEMail: '',
            customerEMailValidation: '',
            books: []
        };

        this.handleCustomerNameChange = this.handleCustomerNameChange.bind(this);
        this.handleCustomerEMailChange = this.handleCustomerEMailChange.bind(this);
        this.orderCustom = this.orderCustom.bind(this);
        this.orderCustomEventSource = this.orderCustomEventSource.bind(this);
        this.orderEventSourceModule = this.orderEventSourceModule.bind(this);
    }

    componentDidMount() {
        axios.get(configuration.url + "/products").then(response => {
            this.setState({
                books: response.data.data.map(function (book) {
                    book.buying = false;
                    return book;
                })
            });
        });
    }

    toggle(book) {
        this.setState(() => {
            return {
                books: this.state.books.map(function (map) {
                    if (map.id === book.id) {
                        map.buying = !map.buying;
                    }

                    return map;
                })
            }
        });
    }

    total() {
        return this.state.books.reduce(function (result, book) {
            return result + (book.buying ? book.price : 0);
        }, 0);
    }

    validate() {
        const email = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        let customerNameValidation = '';
        let customerEMailValidation = '';

        if (!this.state.customerName) {
            customerNameValidation = "can't be blank";
        }

        if (!this.state.customerEMail) {
            customerEMailValidation = "can't be blank";
        }

        if (!customerEMailValidation && !email.test(this.state.customerEMail)) {
            customerEMailValidation = 'not a valid e-mail address';
        }

        this.setState({
            customerNameValidation: customerNameValidation,
            customerEMailValidation: customerEMailValidation
        });

        return !customerNameValidation || !customerEMailValidation;
    }

    handleCustomerNameChange(e) {
        this.setState({
            customerName: e.target.value
        });

        this.validate();
    }

    handleCustomerEMailChange(e) {
        this.setState({
            customerEMail: e.target.value
        });

        this.validate();
    }

    cancel() {
        this._clearOrder();
    }

    _clearOrder() {
        this.setState(() => {
            return {
                books: this.state.books.map(function (map) {
                    map.buying = false;

                    return map;
                })
            }
        });
    }

    orderCustom() {
        this._submitOrder("custom");
    }

    orderCustomEventSource() {
        this._submitOrder("custom / event-source");
    }

    orderEventSourceModule() {
        this._submitOrder("event-source / module");
    }

    _submitOrder(targetSystem) {
        var self = this;

        if (!this.validate()) {
            return false;
        }

        var order = {
            productIds: [],
            targetSystem: targetSystem,
            customerName: this.state.customerName,
            customerEMail: this.state.customerEMail
        };

        this.state.books.forEach(function (book) {
            if (book.buying) {
                order.productIds.push(book.id);
            }
        });

        axios
            .post(configuration.url + "/orders", order)
            .then(() => {
                self._clearOrder();

                state.alerts.add({
                    message: "Your order has been sent for processing.",
                    name: "order-placed"
                });
            })
            .catch(error => {
                state.alerts.add({
                    message: error.message,
                    name: "order-error",
                    type: "danger"
                });
            });
    }

    render() {
        if (!!this.state.books.length) {
            return (
                <div>
                    <h4>Available titles</h4>
                    <table className="table table-sm">
                        <thead className="thead-light">
                            <tr className="row">
                                <th className="col-1"></th>
                                <th className="col">Title</th>
                                <th className="col-2 text-right">Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            {
                                this.state.books.map((book) => {
                                    return (
                                        <tr className={'row ' + (book.buying ? 'table-info' : '')} key={book.id}>
                                            <td className="col-1">
                                                {
                                                    book.buying
                                                        ? <button className="btn btn-default btn-danger btn-sm" onClick={() => this.toggle(book)}>Remove</button>
                                                        : <button className="btn btn-default btn-success btn-sm" onClick={() => this.toggle(book)}>Add</button>
                                                }
                                            </td>
                                            <td className="col"><a href={book.url} target={"_blank"}>{book.description}</a></td>
                                            <td className="col-2 text-right">{book.price}</td>
                                        </tr>
                                    )
                                })
                            }
                        </tbody >
                        <tfoot>
                            <tr className="row">
                                <td colSpan="2" className="col"></td>
                                <td className="col-2 text-right info">{this.total()}</td>
                            </tr>
                        </tfoot>
                    </table >
                    {this.total() > 0 &&
                        (
                            <div>
                                <h4>Checkout</h4>
                                <label htmlFor="customerName">Name</label>
                                <Form.Control value={this.state.customerName} placeholder="Enter your name" trim="true" onChange={this.handleCustomerNameChange} />
                                {!!this.state.customerNameValidation && <div className="text-warning">{this.state.customerNameValidation}</div>}
                                <label htmlFor="customerEMail" className="mt-2">e-mail</label>
                                <Form.Control value={this.state.customerEMail} placeholder="abc.xyz@example.com" type="email" className="mr-1" onChange={this.handleCustomerEMailChange} />
                                {!!this.state.customerEMailValidation && <div className="text-warning">{this.state.customerEMailValidation}</div>}
                                <br />
                                <ButtonToolbar>
                                    <Button onClick={() => this.cancel()} variant="secondary" className="mr-1">Cancel</Button>
                                    <DropdownButton id="dropdown-item-button" title="Order">
                                        <Dropdown.Item as="button" onClick={() => this.orderCustom()}>Custom</Dropdown.Item>
                                        <Dropdown.Item as="button" onClick={() => this.orderCustomEventSource()}>Custom / EventSource</Dropdown.Item>
                                        <Dropdown.Item as="button" onClick={() => this.orderEventSourceModule()}>EventSource / Module</Dropdown.Item>
                                    </DropdownButton>
                                </ButtonToolbar>
                            </div>
                        )
                    }
                </div >
            );
        } else {
            return (
                <Card>
                    <Card.Header>(fetching books)</Card.Header>
                    <Card.Body>
                        <ProgressBar now={100} striped animated className="mt-2" />
                    </Card.Body>
                </Card>
            )
        }
    }
}

// Shuttle.ProcessManagement/site.vuejs/src/components/shuttle-books.vue
<template>
  <div>
    <div v-if="books.length">
      <h4>Available titles</h4>
      <table class="table table-sm">
        <thead class="thead-light">
          <tr class="row">
            <th class="col-1"></th>
            <th class="col">Title</th>
            <th class="col-2 text-right">Price</th>
          </tr>
        </thead>
        <tbody>
          <tr
            v-for="book in books"
            v-bind:key="book.description"
            class="row"
            v-bind:class="{ 'table-info' : book.buying }"
          >
            <td class="col-1">
              <button
                v-if="book.buying"
                v-on:click="toggle(book)"
                class="btn btn-default btn-danger btn-sm"
              >Remove</button>
              <button
                v-else
                v-on:click="toggle(book)"
                class="btn btn-default btn-success btn-sm"
              >Add</button>
            </td>
            <td class="col"><a :href="book.url" target="_blank">{{book.description}}</a></td>
            <td class="col-2 text-right">{{book.price}}</td>
          </tr>
        </tbody>
        <tfoot>
          <tr class="row">
            <td colspan="2" class="col"></td>
            <td class="col-2 text-right info">{{total}}</td>
          </tr>
        </tfoot>
      </table>
      <div v-if="canOrder()">
        <h4>Checkout</h4>
        <label for="customerName">Name</label>
        <b-form-input v-model="customerName" placeholder="Enter your name" trim />
        <div class="text-warning" v-if="!$v.customerName.required">can't be blank</div>
        <label for="customerEMail">e-mail</label>
        <b-form-input
          v-model="customerEMail"
          type="email"
          placeholder="abc.xyz@example.com"
          class="mr-1"
        />
        <div class="text-warning" v-if="!$v.customerEMail.email">is not a valid e-mail</div>
        <div class="text-warning" v-if="!$v.customerEMail.required">can't be blank</div>
        <br />
        <b-button v-on:click="cancel" variant="secondary" class="mr-1">Cancel</b-button>
        <b-dropdown variant="primary" text="Order">
          <b-dropdown-item href="#" v-on:click="orderCustom">Custom</b-dropdown-item>
          <b-dropdown-item href="#" v-on:click="orderCustomEventSource">Custom / EventSource</b-dropdown-item>
          <b-dropdown-item href="#" v-on:click="orderEventSourceModule">EventSource / Module</b-dropdown-item>
        </b-dropdown>
      </div>
      <br />
    </div>
    <div v-else>
      <b-card>
        <h4 slot="header">(fetching books)</h4>
        <b-card-text>
          <b-progress :value="100" striped :animated="true" class="mt-2"></b-progress>
        </b-card-text>
      </b-card>
    </div>
  </div>
</template>

<script>
import axios from "axios";
import configuration from "@/configuration.js";
import { required, email } from "vuelidate/lib/validators";
import state from "@/state.js";

export default {
  name: "shuttle-books",
  data() {
    return {
      customerName: "",
      customerEMail: "",
      books: []
    };
  },
  validations: {
    customerName: {
      required
    },
    customerEMail: {
      required,
      email
    }
  },
  computed: {
    total() {
      return this.books.reduce(function(result, item) {
        return result + (item.buying ? item.price : 0);
      }, 0);
    }
  },
  methods: {
    toggle(book) {
      book.buying = !book.buying;
    },
    canOrder() {
      return this.total > 0;
    },
    cancel() {
      this._clearOrder();
    },
    _clearOrder() {
      this.books.forEach(function(book) {
        book.buying = false;
      });
    },
    orderCustom() {
      this._submitOrder("custom");
    },
    orderCustomEventSource() {
      this._submitOrder("custom / event-source");
    },
    orderEventSourceModule() {
      this._submitOrder("event-source / module");
    },
    _submitOrder: function(targetSystem) {
      var self = this;

      if (this.$v.$invalid) {
        return false;
      }

      var order = {
        productIds: [],
        targetSystem: targetSystem,
        customerName: this.customerName,
        customerEMail: this.customerEMail
      };

      this.books.forEach(function(book) {
        if (book.buying) {
          order.productIds.push(book.id);
        }
      });

      axios
        .post(configuration.url + "/orders", order)
        .then(() => {
          self._clearOrder();

          state.alerts.add({
            message: "Your order has been sent for processing.",
            name: "order-placed"
          });
        })
        .catch(error => {
          state.alerts.add({
            message: error.message,
            name: "order-error",
            type: "danger"
          });
        });
    }
  },
  mounted() {
    axios.get(configuration.url + "/products").then(response => {
      this.books = response.data.data.map(function(book) {
        book.buying = false;
        return book;
      });
    });
  }
};
</script>
