// Shuttle.ProcessManagement/site.react/src/ShuttleBooks.js
import React from 'react';
import axios from "axios";
import configuration from "./configuration.js";
import state from "./state.js";
import Card from 'react-bootstrap/Card'
import ProgressBar from 'react-bootstrap/ProgressBar'
import Form from 'react-bootstrap/Form'
import Button from 'react-bootstrap/Button'
import Dropdown from 'react-bootstrap/Dropdown'
import DropdownButton from 'react-bootstrap/DropdownButton'
import ButtonToolbar from 'react-bootstrap/ButtonToolbar'

export default class ShuttleBooks extends React.Component {
    constructor(props) {
        super(props);

        this.state = {
            customerName: '',
            customerNameValidation: '',
            customerEMail: '',
            customerEMailValidation: '',
            books: []
        };

        this.handleCustomerNameChange = this.handleCustomerNameChange.bind(this);
        this.handleCustomerEMailChange = this.handleCustomerEMailChange.bind(this);
        this.orderCustom = this.orderCustom.bind(this);
        this.orderCustomEventSource = this.orderCustomEventSource.bind(this);
        this.orderEventSourceModule = this.orderEventSourceModule.bind(this);
    }

    componentDidMount() {
        axios.get(configuration.url + "/products").then(response => {
            this.setState({
                books: response.data.data.map(function (book) {
                    book.buying = false;
                    return book;
                })
            });
        });
    }

    toggle(book) {
        this.setState(() => {
            return {
                books: this.state.books.map(function (map) {
                    if (map.id === book.id) {
                        map.buying = !map.buying;
                    }

                    return map;
                })
            }
        });
    }

    total() {
        return this.state.books.reduce(function (result, book) {
            return result + (book.buying ? book.price : 0);
        }, 0);
    }

    validate() {
        const email = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        let customerNameValidation = '';
        let customerEMailValidation = '';

        if (!this.state.customerName) {
            customerNameValidation = "can't be blank";
        }

        if (!this.state.customerEMail) {
            customerEMailValidation = "can't be blank";
        }

        if (!customerEMailValidation && !email.test(this.state.customerEMail)) {
            customerEMailValidation = 'not a valid e-mail address';
        }

        this.setState({
            customerNameValidation: customerNameValidation,
            customerEMailValidation: customerEMailValidation
        });

        return !customerNameValidation || !customerEMailValidation;
    }

    handleCustomerNameChange(e) {
        this.setState({
            customerName: e.target.value
        });

        this.validate();
    }

    handleCustomerEMailChange(e) {
        this.setState({
            customerEMail: e.target.value
        });

        this.validate();
    }

    cancel() {
        this._clearOrder();
    }

    _clearOrder() {
        this.setState(() => {
            return {
                books: this.state.books.map(function (map) {
                    map.buying = false;

                    return map;
                })
            }
        });
    }

    orderCustom() {
        this._submitOrder("custom");
    }

    orderCustomEventSource() {
        this._submitOrder("custom / event-source");
    }

    orderEventSourceModule() {
        this._submitOrder("event-source / module");
    }

    _submitOrder(targetSystem) {
        var self = this;

        if (!this.validate()) {
            return false;
        }

        var order = {
            productIds: [],
            targetSystem: targetSystem,
            customerName: this.state.customerName,
            customerEMail: this.state.customerEMail
        };

        this.state.books.forEach(function (book) {
            if (book.buying) {
                order.productIds.push(book.id);
            }
        });

        axios
            .post(configuration.url + "/orders", order)
            .then(() => {
                self._clearOrder();

                state.alerts.add({
                    message: "Your order has been sent for processing.",
                    name: "order-placed"
                });
            })
            .catch(error => {
                state.alerts.add({
                    message: error.message,
                    name: "order-error",
                    type: "danger"
                });
            });
    }

    render() {
        if (!!this.state.books.length) {
            return (
                <div>
                    <h4>Available titles</h4>
                    <table className="table table-sm">
                        <thead className="thead-light">
                            <tr className="row">
                                <th className="col-1"></th>
                                <th className="col">Title</th>
                                <th className="col-2 text-right">Price</th>
                            </tr>
                        </thead>
                        <tbody>
                            {
                                this.state.books.map((book) => {
                                    return (
                                        <tr className={'row ' + (book.buying ? 'table-info' : '')} key={book.id}>
                                            <td className="col-1">
                                                {
                                                    book.buying
                                                        ? <button className="btn btn-default btn-danger btn-sm" onClick={() => this.toggle(book)}>Remove</button>
                                                        : <button className="btn btn-default btn-success btn-sm" onClick={() => this.toggle(book)}>Add</button>
                                                }
                                            </td>
                                            <td className="col"><a href={book.url} target={"_blank"}>{book.description}</a></td>
                                            <td className="col-2 text-right">{book.price}</td>
                                        </tr>
                                    )
                                })
                            }
                        </tbody >
                        <tfoot>
                            <tr className="row">
                                <td colSpan="2" className="col"></td>
                                <td className="col-2 text-right info">{this.total()}</td>
                            </tr>
                        </tfoot>
                    </table >
                    {this.total() > 0 &&
                        (
                            <div>
                                <h4>Checkout</h4>
                                <label htmlFor="customerName">Name</label>
                                <Form.Control value={this.state.customerName} placeholder="Enter your name" trim="true" onChange={this.handleCustomerNameChange} />
                                {!!this.state.customerNameValidation && <div className="text-warning">{this.state.customerNameValidation}</div>}
                                <label htmlFor="customerEMail" className="mt-2">e-mail</label>
                                <Form.Control value={this.state.customerEMail} placeholder="abc.xyz@example.com" type="email" className="mr-1" onChange={this.handleCustomerEMailChange} />
                                {!!this.state.customerEMailValidation && <div className="text-warning">{this.state.customerEMailValidation}</div>}
                                <br />
                                <ButtonToolbar>
                                    <Button onClick={() => this.cancel()} variant="secondary" className="mr-1">Cancel</Button>
                                    <DropdownButton id="dropdown-item-button" title="Order">
                                        <Dropdown.Item as="button" onClick={() => this.orderCustom()}>Custom</Dropdown.Item>
                                        <Dropdown.Item as="button" onClick={() => this.orderCustomEventSource()}>Custom / EventSource</Dropdown.Item>
                                        <Dropdown.Item as="button" onClick={() => this.orderEventSourceModule()}>EventSource / Module</Dropdown.Item>
                                    </DropdownButton>
                                </ButtonToolbar>
                            </div>
                        )
                    }
                </div >
            );
        } else {
            return (
                <Card>
                    <Card.Header>(fetching books)</Card.Header>
                    <Card.Body>
                        <ProgressBar now={100} striped animated className="mt-2" />
                    </Card.Body>
                </Card>
            )
        }
    }
}

// Shuttle.ProcessManagement/site.angular/src/app/shuttle-books/shuttle-books.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { environment } from '../../environments/environment';
import state from '../state';
import { NgbModule } from '@ng-bootstrap/ng-bootstrap';

@Component({
  selector: 'shuttle-books',
  templateUrl: './shuttle-books.component.html',
  styleUrls: ['./shuttle-books.component.css']
})
export class ShuttleBooksComponent implements OnInit {
  books = [];
  customerName: string;
  customerEMail: string;
  customerNameValidation: string;
  customerEMailValidation: string;

  constructor(
    private http: HttpClient
  ) {
  }

  ngOnInit() {
    this.http.get<any>(environment.url + '/products')
      .subscribe(data => {
        this.books = data.data as [];
      });
  }

  get total() {
    return this.books.reduce((result, item) => {
      return result + (item.buying ? item.price : 0);
    }, 0);
  }

  canOrder() {
    return this.total > 0;
  }

  toggle(book) {
    book.buying = !book.buying;
  }

  get canPlaceOrder() {
    // tslint:disable-next-line: max-line-length
    const email = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;

    this.customerNameValidation = '';
    this.customerEMailValidation = '';

    if (!this.customerName) {
      this.customerNameValidation = 'can\'t be blank';
    }

    if (!this.customerEMail) {
      this.customerEMailValidation = 'can\'t be blank';
    }

    if (!this.customerEMailValidation && !email.test(this.customerEMail)) {
      this.customerEMailValidation = 'not a valid e-mail address';
    }

    return !this.customerNameValidation && !this.customerEMailValidation;
  }

  orderCustom() {
    this.submitOrder('custom');
  }

  orderCustomEventSource() {
    this.submitOrder('custom / event-source');
  }

  orderEventSourceModule() {
    this.submitOrder('event-source / module');
  }

  private submitOrder(targetSystem: string) {
    if (!this.canPlaceOrder) {
      return false;
    }

    const order = {
      productIds: [],
      targetSystem,
      customerName: this.customerName,
      customerEMail: this.customerEMail
    };

    this.books.forEach((book) => {
      if (book.buying) {
        order.productIds.push(book.id);
      }
    });

    this.http
      .post(environment.url + '/orders', order)
      .subscribe(() => {
        this.clearOrder();

        state.alerts.add({
          message: 'Your order has been sent for processing.',
          name: 'order-placed'
        });
      },
      error => {
        state.alerts.add({
          message: error.message,
          name: 'order-error',
          type: 'danger'
        });
      });
  }

  private clearOrder() {
      this.books.forEach((book) => {
        book.buying = false;
      });
  }
}

<div>
    <div *ngIf="books.length">
        <h4>Available titles</h4>
        <table class="table table-sm">
            <thead class="thead-light">
                <tr class="row">
                    <th class="col-1"></th>
                    <th class="col">Title</th>
                    <th class="col-2 text-right">Price</th>
                </tr>
            </thead>
            <tbody>
                <tr *ngFor="let book of books" class="row" [class.table-info]="book.buying">
                    <td class="col-1">
                        <button (click)="toggle(book)" class="btn btn-default btn-sm" [class.btn-danger]="book.buying"
                            [class.btn-success]="!book.buying"><span *ngIf="book.buying">Remove</span><span
                                *ngIf="!book.buying">Add</span></button>
                    </td>
                    <td class="col"><a :href="book.url" target="_blank">{{book.description}}</a></td>
                    <td class="col-2 text-right">{{book.price}}</td>
                </tr>
            </tbody>
            <tfoot>
                <tr class="row">
                    <td colspan="2" class="col"></td>
                    <td class="col-2 text-right info">{{total}}</td>
                </tr>
            </tfoot>
        </table>
        <div *ngIf="canOrder()">
            <h4>Checkout</h4>
            <label for="customerName">Name</label>
            <input [(ngModel)]="customerName" class="form-control" placeholder="Enter your name" trim />
            <div class="text-warning" *ngIf="!!customerNameValidation">{{customerNameValidation}}</div>
            <label for="customerEMail">e-mail</label>
            <input [(ngModel)]="customerEMail" class="form-control mr-1" type="email"
                placeholder="abc.xyz@example.com" />
            <div class="text-warning" *ngIf="!!customerEMailValidation">{{customerEMailValidation}}</div>
            <br />
            <div class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
                <button (click)="cancel" class="btn btn-secondary mr-1">Cancel</button>
                <div ngbDropdown>
                    <button class="btn btn-primary" id="dropdownConfig" ngbDropdownToggle>Toggle</button>
                    <div ngbDropdownMenu aria-labelledby="dropdownConfig">
                        <button ngbDropdownItem (click)="orderCustom()">Custom</button>
                        <button ngbDropdownItem (click)="orderCustomEventSource()">Custom / EventSource</button>
                        <button ngbDropdownItem (click)="orderEventSourceModule()">EventSource / Module</button>
                    </div>
                </div>
            </div>
        </div>
        <br />
    </div>
    <div *ngIf="!books.length">
        <div class="card">
            <div class="card-header">
                <h4>(fetching books)</h4>
            </div>
            <div class="card-body">
                <ngb-progressbar value="1000" class="mt-2" animated="true" striped="true"></ngb-progressbar>
            </div>
        </div>
    </div>
</div>
